### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Amna0099** [ebouJ/E-learning#4]
![error](https://github.com/ebouJ/E-learning/assets/140265805/39c1da4e-1873-44ca-bd3b-61639a41b6cd)

**Comment by ebouJ** [comment]
which branch did you clone? 

A quick fix is to call generateCourse and pass the course as props. I’ll push a fix soon

**Comment by Amna0099** [comment]
Okay thanks

**Comment by ebouJ** [comment]
fixed, rebase from main.
